version: "3.8"

services:
  postgres:
    container_name: pg
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=web-app
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  redis: 
    image: redis
    command: redis-server --requirepass password
    ports: 
      - 6379:6379
    volumes: 
      - redis_db:/var/lib/redis
      - redis_conf:/usr/local/etc/redis/redis.conf

volumes:
  db:
  pgadmin:
  redis_db:
  redis_conf:
