version: "3.8"
  
services:
  webserver:
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/web-app?sslmode=disable"
    image: go-webserver
    restart: unless-stopped
    ports:
      - 4000:4000
    depends_on:
      - "postgres"

  postgres:
    container_name: pg
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=web-app
    expose: 
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
  pgadmin:

