apiVersion: v1
kind: Namespace
metadata:
  name: master

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-deployment
  namespace: master
  labels:
    app: go-web-server
    env: development
spec:
  selector:
    matchLabels:
      app: go
      name: web-server
  replicas: 2
  template:
    metadata:
      labels:
        app: go
        name: web-server
    spec:
      containers:
        - name: go-web-server
          image: cieju/for-kube
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
      imagePullSecrets:
        - name: myregistry

---

apiVersion: v1
kind: Service
metadata: 
  name: go-web-service
spec:
  type: LoadBalancer
  selector:
    app: go
    name: web-server
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
