apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data: 
  POSTGRES_DB: web-server
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

---

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: postgres-pv-volume
  labels: 
    app: web-server-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes: 
    - ReadWWriteMany
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain


