apiVersion: apps/v1
kind: Deployment
metadata: 
  name: go-web-deployment
  namespace: master
  labels:
    app: go-web-server
    env: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go
      name: web-server
  template:
    metadata:
      labels:
        app: go
        name: web-server
    spec:
      containers:
        - name: go-web-server
          image: cieju/for-kube:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
      imagePullSecrets:
        - name: myregistry

---

apiVersion: v1
kind: Service
metadata:
  name: go-web-service
spec:
  selector:
    app: go-webserver 
  ports:
    - protocol: TCP
      port: 4000 
      targetPort: 4000
